# Site settings
title: DLTW
# subtitle: "Unite. Rise. Empower"
url: "" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
timezone: Asia/Kolkata

# icon: /assets/images/logo3.png

# description: District 3190 comprises of 8 Revenue making Districts.

# Build settings
markdown: kramdown
# highlighter: rouge
# permalink: blog/:year/:month/:day/:title/
# paginate: 4
# paginate_path: blog/page-:num/

# Google analytics
# ga_tracking_id: "UA-122171689-6"
# ga_tag_manage_id: "GTM-TTR59PS"

# plugins:
#   - jekyll-sitemap
#   - jekyll-feed

# collections:
#   clubtags:
#     output: true
#     permalink: /:path/

# include:
#   - _redirects