# Site settings
title: DLTW - District Leadership Training Workshop RID 3190
url: "https://dltw.rotaract3190.org"
baseurl: ""
timezone: Asia/Kolkata

description: DLTW - District Leadership Training Workshop is the Annual Distirct Rotaract Training organised by Rotaract District Counil 3190.

og_img: assets/img/og_img.png

include:
  - _redirects

exclude:
  - readme.md